# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: kofu-reactive-mongo

on:
  push:
    paths:
      - "kofu-reactive-mongo/**"
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Setup Postgres in Docker 
      run: |
        docker-compose up -d mongodb
        docker ps -a
    - name: Build with Maven
      run: |
        mvn -B -q clean verify -f kofu-reactive-mongo/pom.xml
