# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: webmvc

on:
  push:
    paths:
      - "webmvc/**"
    branches: [ master ]
  pull_request:
    paths:
      - "webmvc/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Setup MongoDB in Docker 
      run: |
        docker-compose up -d mongodb
        docker ps -a
    - name: Build with Maven
      run: |
        mvn -B -q clean verify -f webmvc/pom.xml
